### ISSUE TITLE
Update X axis in overview (at least) in >= 7 day view to be (or include) date

### ISSUE THREAD

**Issue by mikebroberts** [cloudashdev/cloudash#63]
Right now the X axis shows "time" not "date" in 7 day view ... which isn't so useful since it's not linear. :)

**Comment by mthenw** [comment]
Thanks for reporting! It will be improved in the next release.

**Comment by mthenw** [comment]
Hey, fixed in https://github.com/cloudashdev/cloudash/releases/tag/1.3.0. Just run Cloudash and and it will auto update :)

**Comment by mikebroberts** [comment]
It still shows the time (with the date) in (say) 30 day view, which still seems odd. Would be more useful to have more date labels.
![image](https://user-images.githubusercontent.com/49635/141883475-6e87860e-29bc-4d8c-badc-374fbe94a515.png)
