### ISSUE TITLE
Stuck with loading screen

### ISSUE THREAD

**Issue by markronquillo** [cloudashdev/cloudash#91]
Sorry if this isn't the right place to put it here, but I'm stuck with the loading screen. (see screenshot attached)

Does any one know how to fix this?

<img width="1512" alt="Screen Shot 2022-05-01 at 8 36 21 PM" src="https://user-images.githubusercontent.com/1182515/166146245-03d4ef05-ade8-4f75-8f98-ff7156cf7493.png">
)

**Comment by mthenw** [comment]
Thanks for reporting. We are investigating this issue.

**Comment by mthenw** [comment]
Issue has been fixed in https://github.com/cloudashdev/cloudash/releases/tag/1.14.2

**Comment by serverlesspolska** [comment]
@mthenw  I'm afraid the issue remains. 🙁  What's strange, it never occurred on my computer before
![image](https://user-images.githubusercontent.com/22025007/168615682-17dfea86-dd42-44e3-b02d-5c8e95343fa7.png)

**Comment by mthenw** [comment]
@serverlesspolska I'm looking in that!
